function [H] = get_Hamiltonian(A,B,C,M,N) 
% #========================================================================
% # A,B,C square matrices; M,N integers
% # generate Hamiltonian
% #     H = {H0  H1  0   0  ...
% #          H1  H0  H1  0  ...
% #          0   H1  H0  H1 ...
% #          0   0   H1  H0 ...
% #          ...     ...    ...}_{N*N}
% # where H0 and H1 are given as
% #     H0 = {A  B  0  0 ...
% #           B  A  B  0 ...
% #           0  B  A  B ...
% #           0  0  B  A ...
% #           ...  ...   ...}_{M*M}
% #     H1 = {C  0  0  0 ...
% #           0  C  0  0 ...
% #           0  0  C  0 ...
% #           0  0  0  C ...
% #          ...   ...   ...}_{M*M}
% # respectively.
% #========================================================================
H0 = generate_block_tridiag(A,B,M);
H1 = generate_block_diag(C,M);
H = generate_block_tridiag(H0,H1,N);